### ISSUE TITLE
Local rules in snakemake

### ISSUE THREAD

**Issue by kopardev** [RBL-NCI/RBL_RBL3#2]
Rules like [these](https://github.com/RBL-NCI/RBL_RBL3/blob/24b2b321945c84a255a0d7c0e6e7a681a5db81b2/workflow/Snakefile#L122) can actually be made **local rules** as they do not need much compute resource. We do not need to wait in the slurm queue. See [here](https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html?highlight=local%20rules#local-rules) for details.

**Comment by slsevilla** [comment]
local rules added with commit 69ada85e33eb34676636fe0ebcee0133a47fde5f
